name: Update Release Badge

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest release
        id: release
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)
          echo "version=${LATEST_RELEASE}" >> $GITHUB_OUTPUT

      - name: Update README badges
        run: |
          # This is a placeholder - badges will be automatically updated by shields.io
          echo "Latest release: ${{ steps.release.outputs.version }}"
