name: Sync Documentation to Vector Store

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - "*.md"
      - "*.mdx"
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Run in dry-run mode"
        required: false
        default: false
        type: boolean

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Required for git operations

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for git history

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Sync to OpenAI Vector Store
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_STORE_ID: ${{ secrets.OPENAI_VECTOR_STORE_ID }}
        run: |
          node dist/cli.js sync \
            --provider openai \
            --directory docs \
            --patterns "**/*.md" "**/*.mdx" \
            --exclude "**/test/**" "**/drafts/**" \
            ${{ github.event.inputs.dry-run == 'true' && '--dry-run' || '' }} \
            --verbose
