name: Release Notification

on:
  release:
    types: [published]

permissions:
  contents: read
  actions: write

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send release notification
        run: |
          echo "🎉 New release published: ${{ github.event.release.tag_name }}"
          echo "Release name: ${{ github.event.release.name }}"
          echo "Release URL: ${{ github.event.release.html_url }}"

      - name: Create release summary
        run: |
          cat << EOF > release-summary.txt
          # Vectornator Release ${{ github.event.release.tag_name }}

          A new version of @lukeocodes/vectornator has been released!

          ## What's New
          ${{ github.event.release.body }}

          ## Installation
          \`\`\`bash
          npm install -g @lukeocodes/vectornator@${{ github.event.release.tag_name }}
          \`\`\`

          ## GitHub Action
          \`\`\`yaml
          - uses: lukeocodes/vectornator@${{ github.event.release.tag_name }}
          \`\`\`

          View the full release: ${{ github.event.release.html_url }}
          EOF

      - name: Upload release summary
        uses: actions/upload-artifact@v3
        with:
          name: release-summary
          path: release-summary.txt
